server:
 port: 8080
spring:
 datasource:
  url: jdbc:mysql://38.242.238.254:3306/spring_demo?useSSL=false
  username: spring
  password: K1boswa22!
 jpa:
   show-sql: true
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL5Dialect
     format_sql: true
     use-new-id-generator-mappings: false

